// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tutor.Api.Models
{
    public partial class ApiUser
    {
        [Key]
        public int UserId { get; set; }
        public string ExternalId { get; set; }
        public bool IsStudent { get; set; }
        public bool IsTutor { get; set; }
        public bool IsAdmin { get; set; }

    }
}