// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tutor.Api.Models
{
    public partial class Class
    {
        public Class()
        {
            Topics = new HashSet<Topic>();
        }
        [Key]
        public int Id { get; set; }
        public string ClassCode { get; set; }
        public string ClassName { get; set; }
        public string ClassDesc { get; set; }

        public virtual ICollection<AnsweredQuestion> AnsweredQuestions { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }

        internal static void Seed(tutor_dbContext context, string filename = "Classes.csv")
        {
                // Read the file and update the database
                var classLines = System.IO.File.ReadAllLines($"Content\\{filename}");

                // Load all current words
                var classes = context.Classes.ToDictionary(f => f.ClassCode);

                foreach (var classLine in classLines)
                {
                    var parts = classLine.Split(",");
                    
                        if (!classes.ContainsKey(parts[0]))
                        {
                            context.Classes.Add(new Class { ClassCode = parts[0] });
                        }
                    
                }
                context.SaveChanges();
        }
    }
}