// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tutor.Api.Models
{
    public partial class Class
    {
        public Class()
        {
            AnsweredQuestions = new HashSet<AnsweredQuestion>();
            Questions = new HashSet<Question>();
            Topics = new HashSet<Topic>();
        }

        public int Id { get; set; }
        public string ClassCode { get; set; }
        public string ClassName { get; set; }
        public string ClassDesc { get; set; }

        public virtual ICollection<AnsweredQuestion> AnsweredQuestions { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
    }
}