// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tutor.Api.Models
{
    public partial class Question
    {
        [Key]
        public Guid QuestionId { get; set; }
        public int StudentId { get; set; }
        public int ClassId { get; set; }
        public int TopicId { get; set; }
        public string Question1 { get; set; }

        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
        public virtual Topic Topic { get; set; }

        internal static void Seed(tutor_dbContext context)
        {
            if(context.Questions.Count() < 1) 
            { 
                Question q = new Question();
                q.QuestionId = Guid.NewGuid();
                q.ClassId = 1;
                q.StudentId = 0;
                q.TopicId = 1;
                q.Question1 = "This is a test question";

                context.Questions.Add(q);
                context.SaveChanges();
            }
        }
    }
   
}