// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tutor.Api.Models
{
    public partial class Question
    {
        public Guid QuestionId { get; set; }
        public int StudentId { get; set; }
        public int ClassId { get; set; }
        public int TopicId { get; set; }
        public string Question1 { get; set; }

        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
        public virtual Topic Topic { get; set; }
    }
}