// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tutor.Api.Models
{
    public partial class Topic
    {
        [Key]
        public int Id { get; set; }
        public int ClassId { get; set; }
        public string Topic1 { get; set; }


        internal static void Seed(tutor_dbContext context)
        {
            var topics = context.Topics.ToDictionary(x => x.Topic1);
            if (!topics.ContainsKey("Lists"))
            {
                Topic t = new();
                t.ClassId = 1;
                t.Topic1 = "Lists";


                context.Topics.Add(t);
                context.SaveChanges();
            }
        }
    }
}