// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tutor.Api.Models
{
    public partial class Topic
    {
        public Topic()
        {
            AnsweredQuestions = new HashSet<AnsweredQuestion>();
            Questions = new HashSet<Question>();
        }
        [Key]
        public int Id { get; set; }
        public int ClassId { get; set; }
        public string Topic1 { get; set; }

        public virtual Class Class { get; set; }
        public virtual ICollection<AnsweredQuestion> AnsweredQuestions { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}